# Generated by Django 4.2.6 on 2023-12-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Music',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='title',
            new_name='name',
        ),
    ]
