# Generated by Django 4.2.6 on 2023-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_game_music_rename_title_music_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
